### ISSUE TITLE
Build failed .. fontcase-explorer/assets/icons doesn't contain icons

### ISSUE THREAD

**Issue by thinkholic** [fontcase/fontcase-explorer#26]
On `npm run prod`:

```
Error: Exit code: 1. Command failed: /Users/jarvis/Library/Caches/electron-builder/app-builder/app-builder-v0.6.0-x64/app-builder icon --format icns --root /Users/jarvis/Dev/apps/fontcase-apps/fontcase-explorer/assets --root /Users/jarvis/Dev/apps/fontcase-apps/fontcase-explorer --input /Users/jarvis/Dev/apps/fontcase-apps/fontcase-explorer/assets/icons
   ⨯ icon directory /Users/jarvis/Dev/apps/fontcase-apps/fontcase-explorer/assets/icons doesn't contain icons
github.com/develar/app-builder/icons.ConvertIcon
	/Users/develar/go/src/github.com/develar/app-builder/icons/icon-converter.go:161
main.doConvertIcon
	/Users/develar/go/src/github.com/develar/app-builder/main.go:61
main.main
	/Users/develar/go/src/github.com/develar/app-builder/main.go:44
runtime.main
	/usr/local/Cellar/go/1.9.2/libexec/src/runtime/proc.go:195
runtime.goexit
	/usr/local/Cellar/go/1.9.2/libexec/src/runtime/asm_amd64.s:2337


   ⨯ icon directory /Users/jarvis/Dev/apps/fontcase-apps/fontcase-explorer/assets/icons doesn't contain icons
github.com/develar/app-builder/icons.ConvertIcon
	/Users/develar/go/src/github.com/develar/app-builder/icons/icon-converter.go:161
main.doConvertIcon
	/Users/develar/go/src/github.com/develar/app-builder/main.go:61
main.main
	/Users/develar/go/src/github.com/develar/app-builder/main.go:44
runtime.main
	/usr/local/Cellar/go/1.9.2/libexec/src/runtime/proc.go:195
runtime.goexit
	/usr/local/Cellar/go/1.9.2/libexec/src/runtime/asm_amd64.s:2337


    at /Users/jarvis/Dev/apps/fontcase-apps/fontcase-explorer/node_modules/builder-util/src/util.ts:122:16
    at ChildProcess.exithandler (child_process.js:282:5)
    at emitTwo (events.js:126:13)
    at ChildProcess.emit (events.js:214:7)
    at maybeClose (internal/child_process.js:925:16)
    at Socket.stream.socket.on (internal/child_process.js:346:11)
    at emitOne (events.js:116:13)
    at Socket.emit (events.js:211:7)
    at Pipe._handle.close [as _onclose] (net.js:554:12)
From previous event:
    at exec (/Users/jarvis/Dev/apps/fontcase-apps/fontcase-explorer/node_modules/builder-util/src/util.ts:85:3)
    at /Users/jarvis/Dev/apps/fontcase-apps/fontcase-explorer/node_modules/electron-builder-lib/src/platformPackager.ts:587:23
    at Generator.next (<anonymous>)
    at LOOP (fs.js:1745:14)
    at _combinedTickCallback (internal/process/next_tick.js:131:7)
    at process._tickCallback (internal/process/next_tick.js:180:9)
From previous event:
    at MacPackager.resolveIcon (/Users/jarvis/Dev/apps/fontcase-apps/fontcase-explorer/node_modules/electron-builder-lib/out/platformPackager.js:626:11)
    at /Users/jarvis/Dev/apps/fontcase-apps/fontcase-explorer/node_modules/electron-builder-lib/src/platformPackager.ts:572:28
    at Generator.next (<anonymous>)
    at go$readdir$cb (/Users/jarvis/Dev/apps/fontcase-apps/fontcase-explorer/node_modules/graceful-fs/graceful-fs.js:149:14)
    at FSReqWrap.oncomplete (fs.js:135:15)
From previous event:
    at MacPackager.getOrConvertIcon (/Users/jarvis/Dev/apps/fontcase-apps/fontcase-explorer/node_modules/electron-builder-lib/out/platformPackager.js:597:11)
    at Lazy.MacPackager._iconPath.Lazy (/Users/jarvis/Dev/apps/fontcase-apps/fontcase-explorer/node_modules/electron-builder-lib/src/macPackager.ts:23:43)
    at Lazy.get value [as value] (/Users/jarvis/Dev/apps/fontcase-apps/fontcase-explorer/node_modules/lazy-val/src/main.ts:18:23)
    at /Users/jarvis/Dev/apps/fontcase-apps/fontcase-explorer/node_modules/electron-builder-lib/src/macPackager.ts:53:27
    at Generator.next (<anonymous>)
From previous event:
    at MacPackager.getIconPath (/Users/jarvis/Dev/apps/fontcase-apps/fontcase-explorer/node_modules/electron-builder-lib/out/macPackager.js:138:11)
    at /Users/jarvis/Dev/apps/fontcase-apps/fontcase-explorer/node_modules/electron-builder-lib/src/packager/mac.ts:67:31
    at Generator.next (<anonymous>)
    at /Users/jarvis/Dev/apps/fontcase-apps/fontcase-explorer/node_modules/graceful-fs/graceful-fs.js:78:16
    at FSReqWrap.readFileAfterClose [as oncomplete] (fs.js:511:3)
From previous event:
    at createMacApp (/Users/jarvis/Dev/apps/fontcase-apps/fontcase-explorer/node_modules/electron-builder-lib/out/packager/mac.js:142:21)
    at /Users/jarvis/Dev/apps/fontcase-apps/fontcase-explorer/node_modules/electron-builder-lib/src/platformPackager.ts:203:13
    at Generator.next (<anonymous>)
    at runCallback (timers.js:789:20)
    at tryOnImmediate (timers.js:751:5)
    at processImmediate [as _immediateCallback] (timers.js:722:5)
From previous event:
    at MacPackager.doPack (/Users/jarvis/Dev/apps/fontcase-apps/fontcase-explorer/node_modules/electron-builder-lib/out/platformPackager.js:284:11)
    at /Users/jarvis/Dev/apps/fontcase-apps/fontcase-explorer/node_modules/electron-builder-lib/src/macPackager.ts:90:63
    at Generator.next (<anonymous>)
From previous event:
    at MacPackager.pack (/Users/jarvis/Dev/apps/fontcase-apps/fontcase-explorer/node_modules/electron-builder-lib/out/macPackager.js:200:11)
    at /Users/jarvis/Dev/apps/fontcase-apps/fontcase-explorer/node_modules/electron-builder-lib/src/packager.ts:364:24
    at Generator.next (<anonymous>)
    at xfs.stat (/Users/jarvis/Dev/apps/fontcase-apps/fontcase-explorer/node_modules/fs-extra-p/node_modules/fs-extra/lib/mkdirs/mkdirs.js:56:16)
    at /Users/jarvis/Dev/apps/fontcase-apps/fontcase-explorer/node_modules/graceful-fs/polyfills.js:287:18
    at FSReqWrap.oncomplete (fs.js:153:5)
From previous event:
    at Packager.doBuild (/Users/jarvis/Dev/apps/fontcase-apps/fontcase-explorer/node_modules/electron-builder-lib/out/packager.js:432:11)
    at /Users/jarvis/Dev/apps/fontcase-apps/fontcase-explorer/node_modules/electron-builder-lib/src/packager.ts:308:52
    at Generator.next (<anonymous>)
    at /Users/jarvis/Dev/apps/fontcase-apps/fontcase-explorer/node_modules/graceful-fs/graceful-fs.js:99:16
    at /Users/jarvis/Dev/apps/fontcase-apps/fontcase-explorer/node_modules/graceful-fs/graceful-fs.js:43:10
    at FSReqWrap.oncomplete (fs.js:135:15)
From previous event:
    at Packager._build (/Users/jarvis/Dev/apps/fontcase-apps/fontcase-explorer/node_modules/electron-builder-lib/out/packager.js:376:11)
    at /Users/jarvis/Dev/apps/fontcase-apps/fontcase-explorer/node_modules/electron-builder-lib/src/packager.ts:270:23
    at Generator.next (<anonymous>)
    at runCallback (timers.js:789:20)
    at tryOnImmediate (timers.js:751:5)
    at processImmediate [as _immediateCallback] (timers.js:722:5)
From previous event:
    at Packager.build (/Users/jarvis/Dev/apps/fontcase-apps/fontcase-explorer/node_modules/electron-builder-lib/out/packager.js:332:11)
    at /Users/jarvis/Dev/apps/fontcase-apps/fontcase-explorer/node_modules/electron-builder/src/builder.ts:310:40
    at Generator.next (<anonymous>)
From previous event:
    at _build (/Users/jarvis/Dev/apps/fontcase-apps/fontcase-explorer/node_modules/electron-builder/out/builder.js:61:21)
    at build (/Users/jarvis/Dev/apps/fontcase-apps/fontcase-explorer/node_modules/electron-builder/src/builder.ts:280:10)
    at then (/Users/jarvis/Dev/apps/fontcase-apps/fontcase-explorer/node_modules/electron-builder/src/cli/cli.ts:48:33)
    at runCallback (timers.js:789:20)
    at tryOnImmediate (timers.js:751:5)
    at processImmediate [as _immediateCallback] (timers.js:722:5)
From previous event:
    at Object.args [as handler] (/Users/jarvis/Dev/apps/fontcase-apps/fontcase-explorer/node_modules/electron-builder/src/cli/cli.ts:48:33)
    at Object.runCommand (/Users/jarvis/Dev/apps/fontcase-apps/fontcase-explorer/node_modules/electron-builder/node_modules/yargs/lib/command.js:235:44)
    at Object.parseArgs [as _parseArgs] (/Users/jarvis/Dev/apps/fontcase-apps/fontcase-explorer/node_modules/electron-builder/node_modules/yargs/yargs.js:1041:24)
    at Object.get [as argv] (/Users/jarvis/Dev/apps/fontcase-apps/fontcase-explorer/node_modules/electron-builder/node_modules/yargs/yargs.js:957:21)
    at Object.<anonymous> (/Users/jarvis/Dev/apps/fontcase-apps/fontcase-explorer/node_modules/electron-builder/src/cli/cli.ts:42:15)
    at Module._compile (module.js:643:30)
    at Object.Module._extensions..js (module.js:654:10)
    at Module.load (module.js:556:32)
    at tryModuleLoad (module.js:499:12)
    at Function.Module._load (module.js:491:3)
    at Function.Module.runMain (module.js:684:10)
    at startup (bootstrap_node.js:187:16)
    at bootstrap_node.js:608:3
```

**Comment by thinkholic** [comment]
Closed by @THPubs
